name: Build Ruby Gem

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4

    - name: Build and test
      run: |
        gem install bundler
        bundle install
        bundle exec rspec
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    - name: Notify Slack
      uses: adamkdean/simple-slack-notify@1.0.4
      with:
        channel: '#ops'
        username: 'GitHub Actions'
        color: 'good'
        text: 'A new version of the maltese gem has been built.'
